### ISSUE TITLE
Adamantine Farmable With Silk Touch

### ISSUE THREAD

**Issue by milkev** [ColMarek/adamantine#3]
if you use silk touch on a diamond ore you can still get adamantine ore from it, place the diamond ore down again and repeat until you have enough adamantine to fill your entire house with blocks of it.

**Comment by ColMarek** [comment]
The ore will never drop when the pick used has silk touch.

**Comment by milkev** [comment]
![Adamantine From Diamond](https://user-images.githubusercontent.com/22010128/78706280-0d4c7f00-78cc-11ea-9399-182247694c0d.gif)
?????

**Comment by milkev** [comment]
ah, update was released fixing it. thanks good sir. sry!
